♻️ Save extracted street_2 data when splitting street_1
MyParcelCOM/microservice-skeleton pull request #291
Opened 2022-06-14 11:35 UTC by M4tini

The address splitter puts leftover data from `street_1` into `additionToAddress2` which is ignored in our implementation so far.
We should respect this extracted data and put it in our `street_2`.

Note: this leftover data in `street_2` will be overwritten if the provided shipment has `street_2` as well, but I think that's fine.

2022-06-15 13:56 UTC, yoan-myparcel approved these changes

2022-06-15 13:59 UTC, yoan-myparcel requested changes

2022-06-15 13:59 UTC, yoan-myparcel commented on app/PickUpDropOffLocations/Address.php
> +                $this->setStreet2(Arr::get($addressBreakdown, 'additionToAddress2'));
I have a suggestion here actually. Lets first check if street2 is empty and then set the addition. Otherwise lets prepend it instead of overwriting it.

I think the following one-liner can apply for these cases:
```suggestion
                $this->setStreet2(trim(Arr::get($addressBreakdown, 'additionToAddress2') . ' ' . $this->street2));
```

2022-06-15 17:21 UTC, M4tini commented on app/PickUpDropOffLocations/Address.php
> +                $this->setStreet2(Arr::get($addressBreakdown, 'additionToAddress2'));
I think that would be nice. However, we always call `setStreet2()` after `setStreet1()`. How do we nicely handle:
```
->setStreet1('Street 1 A')
->setStreet2('Building B')
```
I actually regret we made this setter so complex. It could have been a `splitStreet()` function which we would only call in the microservices that actually need this data to be separated. The majority of them implodes everything and we had to manually deactivate the splitting there because of the data going missing or the order of street elements being changed.

2022-06-20 06:50 UTC, yoan-myparcel approved these changes

2022-06-20 06:50 UTC, merged