MP-4899 ✨ introduced statuspublisher to push statuses to sns
MyParcelCOM/microservice-skeleton pull request #344
Opened 2023-05-04 13:08 UTC by zwaans

# Changes
- Introduced logic to push statuses to SNS

Added this ticket to discuss the reference to the shipment in the status message:
https://myparcelcombv.atlassian.net/browse/MP-5860

2023-05-04 15:12 UTC, NickVries requested changes

2023-05-04 15:12 UTC, NickVries commented on app/Providers/AppServiceProvider.php
> +//        });
I don't think this is that necessary is it? 
Leaving this uncommented would not affect any microservices that don't use SNS. 
As long as the StatusPublisher class isn't used, nothing will happen with SNS, right?

2023-05-04 15:12 UTC, NickVries commented on routes/api.php
> +//   ->name('get-collection-time-slots');
Unexpected change here? Why did you decide to do this?

2023-05-04 15:14 UTC, NickVries commented on app/Statuses/StatusPublisher.php
> +                    'status'        => $status,
If we want the API to be able to handle these statuses as easy as possible, it's probably a good idea to transform them in the exact same way we transform the statuses that are returned via the endpoint.

2023-05-04 15:16 UTC, zwaans commented on app/Providers/AppServiceProvider.php
> +//        });
Its not necessary from a coding viewpoint however it might be a slight optimization to leave it out since it won't instantiate a statuspublisher if not needed and therefore might save a bit of memory.

2023-05-04 15:16 UTC, zwaans commented on routes/api.php
> +//   ->name('get-collection-time-slots');
I thought this was a mistake on our end, if we don't have collections on a microservice then why should be expose this endpoint

2023-05-08 09:20 UTC, NickVries commented on app/Providers/AppServiceProvider.php
> +//        });
Is the idea behind using these callbacks not that they are only activated once it's necessary? 
I think the optimization is so small that it doesn't really outweigh the inconvenience of having to comment this out in every microservice. 

Having said that, I also don't deem this important enough to make or break this PR. I will leave you to decide what to do with it.

2023-05-08 09:22 UTC, NickVries commented
I realized from your last commit that there's no tests for the StatusPublisher. 

Can you add some simple tests that ensure that the published message is equal to a certain format?

2023-05-08 10:26 UTC, zwaans commented on app/Providers/AppServiceProvider.php
> +//        });
I can give you another argument. If a microservice isn't going to use the Sns setup then we won't add the service account with the permissions to the container running the microservice because why would we give the container access to SNS if it doesn't need it. If we don't insert the service account on the container the instantiation of the SnsClient will still try and authenticate with AWS and probably throw an error because it isn't authorized to do so, this would mean we would see error messages related to this authentication which would add noise in the error channels.

2023-05-10 08:06 UTC, NickVries requested changes

2023-05-10 08:06 UTC, NickVries commented on tests/Feature/StatusPublisherTest.php
> +        $this->snsClient->shouldReceive('publishBatchAsync')->once()->andReturn(new Promise());
I'd like to see what arguments are given to the `publishBatchAsync` method here.
Would you mind adding a `::with()` assertion that tests the arguments?

2023-05-10 12:48 UTC, NickVries approved these changes

2023-05-10 12:48 UTC, merged