:sparkles: add GET PUDO by ID endpoint
MyParcelCOM/microservice-skeleton pull request #367
Opened 2023-10-25 11:44 UTC by yoerriwalstra

## Changes
- add `GET /pickup-dropoff-locations/{pudo_id}` endpoint
- add method `getById` to PickUpDropOffLocationRepository
- add tests (mark as skipped)

## Related Jira issue
https://myparcelcombv.atlassian.net/browse/MP-5579

2023-10-26 13:14 UTC, zwaans requested changes

2023-10-26 13:14 UTC, zwaans commented on app/PickUpDropOffLocations/PickUpDropOffLocationController.php
> +            return new JsonResponse($transformerService->transformResources($location));
Shouldn't we use `transformResource` here? I thought `transformResources` would include pagination in the response.

2023-10-26 13:14 UTC, zwaans commented on app/PickUpDropOffLocations/PickUpDropOffLocationController.php
> +        if ($location->count()) {
Why `->count` and not something like `isset()`, reads better imo

2023-10-26 13:14 UTC, zwaans commented on app/PickUpDropOffLocations/PickUpDropOffLocationRepository.php
> +    public function getById(string $pickUpDropOffLocationId): ResourcesInterface
This function should return an instance of a model and not a `ResourcesInterface`, its always returning a single resource

2023-10-27 07:56 UTC, yoerriwalstra commented on app/PickUpDropOffLocations/PickUpDropOffLocationController.php
> +            return new JsonResponse($transformerService->transformResources($location));
did not know about that. fixed

2023-10-27 07:57 UTC, yoerriwalstra commented on app/PickUpDropOffLocations/PickUpDropOffLocationController.php
> +        if ($location->count()) {
because I returned a Collection before, but since I now return a Model instance, I have updated the condition to
```
if (!$location) { ... }
```

2023-10-27 07:57 UTC, yoerriwalstra commented on app/PickUpDropOffLocations/PickUpDropOffLocationRepository.php
> +    public function getById(string $pickUpDropOffLocationId): ResourcesInterface
done

2023-10-27 08:15 UTC, zwaans commented on app/PickUpDropOffLocations/PickUpDropOffLocationController.php
> +        if ($location->count()) {
`!location` is still a check to see if its `null` so I assume you can still use `isset()`

2023-10-27 08:17 UTC, zwaans requested changes

2023-10-27 08:17 UTC, zwaans commented on tests/Unit/PickUpDropOffLocations/PickUpDropOffLocationRepositoryTest.php
> +        $this->assertInstanceOf(ResourcesInterface::class, $resources);
I think we have to update this assertion as well

2023-10-27 08:22 UTC, yoerriwalstra commented on tests/Unit/PickUpDropOffLocations/PickUpDropOffLocationRepositoryTest.php
> +        $this->assertInstanceOf(ResourcesInterface::class, $resources);
done

2023-10-27 10:54 UTC, zwaans approved these changes

2023-10-27 10:54 UTC, merged