✨ Service rates can have options with a price
MyParcelCOM/microservice-skeleton pull request #388
Opened 2024-10-15 10:59 UTC by M4tini

https://myparcelcombv.atlassian.net/browse/MP-6848
---
The service-rates response from our microservices currently consists of:
- `price` populated with the carrier's price, minus the fuel surcharge
- `fuel_surcharge`

We want them to be able to consist of:
- `price` populated with the carrier's price, minus the fuel surcharge, minus the option price(s)
- `fuel_surcharge`
- `options` which could have their own `price` (basically a copy of the options array from the received shipment data)

2024-10-15 11:56 UTC, yoan-myparcel requested changes

2024-10-15 11:56 UTC, yoan-myparcel commented on app/ServiceRates/ServiceRate.php
> +    protected array $options = [];
Now Option has price, although it does not really need it in any other case, it could be confusing don't you think?

What if we introduce a new subclass of Option called OptionPrice in the ServiceRates folder, or even better - have Option (or OptionPrice again) in ServiceRates that has price as a property and Option from Shipments as another property. That way they are kept separated. 

By doing that you can make the price in OptionPrice mandatory instead of optional which will avoid `null` checks.

2024-10-15 13:35 UTC, M4tini commented on app/ServiceRates/ServiceRate.php
> +    protected array $options = [];
Good idea, I'm going to refactor some things, hold on

2024-10-16 12:56 UTC, yoan-myparcel approved these changes

2024-10-16 12:56 UTC, merged